### ISSUE TITLE
Remix IDE 文档翻译 [rest part]

### ISSUE THREAD

**Issue by drafish** [PlanckerLabs/remix-cc#12]
- 网站地址：https://remix-ide.readthedocs.io/en/latest/index.html
- 仓库地址：https://github.com/ethereum/remix-ide
- crowdin 地址：https://crowdin.com/project/remix-translation/zh-CN

@gongzishuye 同学已经领了下面4个模块的翻译任务，其他同学想领翻译任务的话就在评论区里回复，我再建新任务。
- [x] Hardhat
- [x] Truffle
- [x] Slither
- [x] Foundry

**Comment by gongzishuye** [comment]
OK，我认领这四个模块的翻译任务

**Comment by drafish** [comment]
@gongzishuye 同学已完成了所有存量翻译工作。这个 issue 可以关闭了
