### ISSUE TITLE
Remix 官网国际化与中文翻译

### ISSUE THREAD

**Issue by drafish** [PlanckerLabs/remix-cc#5]
- 网站地址：https://remix-project.org/
- 仓库地址：https://github.com/ethereum/remix-website/tree/master

这个网站是用 React 开发的，就只有一个页面。先把国际化和中文翻译做了，然后给 Remix 团队提个 PR 。这事儿做完以后，我会再建个 issue ，搞国内的分支。把上面的链接还有团队信息都替换成国内的。

- [x] 国际化 feature 开发 （建议使用 [react-intl](https://formatjs.io/docs/react-intl/) 开发，以太坊官网和 Remix Online IDE 用的都是这个）
- [x] 中文翻译

**Comment by SpokieKid** [comment]
我在尝试第一个 todo
