### ISSUE TITLE
chinese corrections for remix-workshops

### ISSUE THREAD

**Issue by drafish** [PlanckerLabs/remix-cc#55]
Hi @ryestew (Rob) ! 
I created [a branch for corrections](https://github.com/PlanckerLabs/remix-workshops/tree/corrections) based on master, and I'v already cut and pasted corrections in this branch. It's easy to locate the source string in english docs. There are some mistakes of markdown signs in those corrections which I'v already fixed that in `corrections` branch.

I will ask @gongzishuye (Mocca) to merge this branch to china. It should be easy to see which string is corrected.

Here are the corrections files that Rob sent to me.
[remix-basic.txt](https://github.com/PlanckerLabs/remix-cc/files/12387369/remix-basic.txt)
[deploy-with-libraries.txt](https://github.com/PlanckerLabs/remix-cc/files/12387370/deploy-with-libraries.txt)
[ERC20TokenCourse.txt](https://github.com/PlanckerLabs/remix-cc/files/12387371/ERC20TokenCourse.txt)
[ERC721Auction.txt](https://github.com/PlanckerLabs/remix-cc/files/12387372/ERC721Auction.txt)
[recorder.md](https://github.com/PlanckerLabs/remix-cc/files/12387373/recorder.md)
[NFTTokenCourse.md](https://github.com/PlanckerLabs/remix-cc/files/12387374/NFTTokenCourse.md)

Mocca, you need to check if I missed any strings in  [corrections branch](https://github.com/PlanckerLabs/remix-workshops/tree/corrections), before you merge it into china branch. 

I suggest that we can rename the branch name from `china` to `zh`. I mean china is not a language, it's a country. I think it's better if we rename the branch with language code.

Rob, I'm sorry about the quality of our translations. I didn't expect any corrections from you. We will double check the transactions. And, may I ask where did you get the corrections. I mean whoever gave it to you, he must be good at chinese. He or she should join us, join Remix CC. And I think you can put remix-workshops on crowdin. It will be easier for translators to collaborate.

**Comment by ryestew** [comment]
Here are a few more corrections - I think this will be the last document of corrections.

[SolidityBeginnerCourseWeb3Client.md](https://github.com/PlanckerLabs/remix-cc/files/12341674/SolidityBeginnerCourseWeb3Client.md)

**Comment by drafish** [comment]
> Here are a few more corrections - I think this will be the last document of corrections.
> 
> [SolidityBeginnerCourseWeb3Client.md](https://github.com/PlanckerLabs/remix-cc/files/12341674/SolidityBeginnerCourseWeb3Client.md)

OK, I'v already add these corrections into corrections branch. @gongzishuye Don't forget to check this one.
