### ISSUE TITLE
Remix IDE 文档翻译 [Part One]

### ISSUE THREAD

**Issue by drafish** [PlanckerLabs/remix-cc#6]
- 网站地址：https://remix-ide.readthedocs.io/en/latest/index.html
- 仓库地址：https://github.com/ethereum/remix-ide
- crowdin 地址：https://crowdin.com/project/remix-translation/zh-CN

和以太坊官网一样，Remix IDE 文档也是用 crowdin 来协作翻译。现在翻译完成度只有 54%，有一部分是 Remix 团队自己翻译的，还有一部分是我翻译的。已翻译的那部分需要校对，不过这个优先级不高。我们先把未翻译的那部分给翻译完。

- [x] Deploy & Run Proxy Contracts
- [x] Debugger
- [x] Solidity Static Analysis
- [x] Unit Testing Plugin
- [x] Command Line Interface
- [x] Remix Assert Library
- [x] Testing by Example

@gongzishuye 同学已经领了上面7个模块的翻译任务，其他同学想领翻译任务的话就在评论区里回复，我再建新任务。

**Comment by gongzishuye** [comment]
hello 我可以继续文档翻译的工作

**Comment by gongzishuye** [comment]
@drafish 我已经完成了上面7个模块的翻译任务，继续申领 [NATIVE EXTERNAL INTEGRATIONS](https://remix-ide.readthedocs.io/en/latest/hardhat.html) 板块下面的四篇文档：

- Hardhat
- Truffle
- Slither
- Foundry
