### ISSUE TITLE
重制 Remix 团队发布在 YouTube 上的短视频

### ISSUE THREAD

**Issue by drafish** [PlanckerLabs/remix-cc#9]
- [ ] [Proxy Contracts in Remix](https://www.youtube.com/watch?v=YJZV9uiDbJI)
- [ ] [Using Remix with Hardhat](https://www.youtube.com/watch?v=8adSqvhvumQ)
- [ ] [Connecting Remix Online IDE to Your Computer Filesystem](https://www.youtube.com/watch?v=2OAx2UoLYEI)
- [ ] [Solidity Unit Testing in Remix](https://www.youtube.com/watch?v=p7yjjynRJAQ)
- [ ] [Using the Remix ETHDoc Generator/Viewer](https://www.youtube.com/watch?v=UkMqdI7TGxw)
- [ ] [Compile and Run a Script with Remix](https://www.youtube.com/watch?v=ZR8sh7MRDQ4)
- [ ] [Transaction Recorder in Remix](https://www.youtube.com/watch?v=GchvmIRSxUo)
- [ ] [Running a Script from Remix](https://www.youtube.com/watch?v=Eh1qgOurDxU)
- [ ] [How to use: Remix VSCode Extension](https://www.youtube.com/watch?v=tcnpGeOiA_M)

这9个视频就是 Remix 团队在 YouTube 上发布的所有视频了。每个视频都会介绍 Remix IDE 的一个小功能点，平均两三分钟的样子。我们先把这9个视频用中文重新制作一遍。其中 `Connecting Remix Online IDE to Your Computer Filesystem` 这个视频就是我做的，Remix 团队的 Rob 做了英文配音，并加了片头和片尾。我手上有中文原版的视频，加个片头片尾就能用了。

Remix IDE 的功能是非常多的，这9个视频是远远不够的。我问了 Rob ，他说大概一年需要做 25 个视频。

等这9个视频制作完后，我再问 Rob 要一些他们计划要做但还没做的视频主题过来。新视频制作比老视频翻拍要麻烦很多。主要在于内容很不好定。

比如之前 Rob 发我的几个主题中有一个是 `Cloning a repo` 。我知道怎么克隆一个仓库，如果只是展示一下怎么克隆仓库，那 30 秒都不用。可如果展开讲的话，那3分钟又不够用了。具体一个视频要展现哪些内容，这个非常需要斟酌。以后新视频的话，我会一个视频发一个 issue 。

**Comment by SpokieKid** [comment]
这里重新用中文制作一遍，是指配音 + 字幕，还是仅仅是字幕？如果仅仅是字幕的话那么可以我可以很快协助完成。

**Comment by drafish** [comment]
最完美的做法应该是用中文界面重新录制，加上中文配音和字幕。但这个成本是最高的。退而求其次的话，就是配音+字幕。再次一点的话就只加个中文字幕。
要我说的话，都可以。能做到什么程度就做到什么程度。如果只加字幕很快的话，可以先做个版本出来看看效果。 @SpokieKid

**Comment by SpokieKid** [comment]
好，我先做字幕看看效果。

**Comment by drafish** [comment]
这个 issue 先关掉了。现在决定不再重制，而是加中文字幕，这里面会涉及到视频剪辑和翻译。我会写个文档，把整个制作过程写清楚。
